project/clientes/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'clientes'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('cliente/<int:pk>/update', views.ClientUpdate.as_view(), name='cliente_update'),
    path('cliente/<int:pk>/detail', views.ClienteDetail.as_view(), name='cliente_detail'),
]

urlpatterns += staticfiles_urlpatterns()

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('ordenes/', include('ordenes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

urlpatterns += [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('register/', views.register, name='register'),
]

urlpatterns += staticfiles_urlpatterns()

project/clientes/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')
    phone = models.CharField(max_length=50, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', default='project/core/static/core/img/avatar_default.webp', null=True, blank=True)

project/clientes/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import UpdateView, DetailView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.db.models import Q
from core.forms import CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login
from . import models

class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff
    
    def handle_no_permission(self):
        return redirect('clientes:home')

def not_staff(user):
    return user.is_staff

@login_required
@user_passes_test(not_staff)
def home(request):
    consulta = request.GET.get('consulta')
    if consulta:
        clientes = User.objects.filter(
            Q(first_name__icontains=consulta) | Q(last_name__icontains=consulta),
            is_staff=False
        )
    else:
        clientes = User.objects.filter(is_staff=False)
    context = {
        'clientes': clientes,
        'consulta_actual': consulta
    }
    if 'limpiar' in request.GET:
        return redirect('clientes:home')
    return render(request, 'clientes/index.html', context)

class ClienteDetail(LoginRequiredMixin, StaffRequiredMixin, DetailView):
  model = models.Client
  context_object_name = 'cliente'

class ClientUpdate(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'clientes/client_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        new_password = form.cleaned_data.get('password')
        if new_password:
            user.set_password(new_password)
        user.save()

        if not self.request.user.is_staff:
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            update_session_auth_hash(self.request, user) 

        return super().form_valid(form)
    
    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy('clientes:home')
        else:
            return reverse_lazy('core:home')

project/clientes/templates/clientes/client_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
Cliente: {{ cliente.user.first_name }} | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center gap-4 w-100">
  <div class="d-flex flex-column align-items-center border border-1 rounded-2 w-50 py-4 px-5 shadow-sm bg-light">
    <h2 class="mb-4 fs-2">Cliente: {{ cliente.user.first_name }} {{ cliente.user.last_name }}</h2>
    <div class="d-flex w-100 gap-4 justify-content-between ">
      <div class="d-flex flex-column">
        {% if cliente.avatar %}
        <img src="{{ cliente.avatar.url }}" alt="Avatar del cliente" style="width: 250px; border-radius: 10px;">
        {% else %}
        <img src="{% static 'core/img/default-product.webp' %}" alt="Imagen del producto por defecto"
          style="width: 250px; border-radius: 10px;">
        {% endif %}
      </div>
      <div class="d-flex flex-column w-100">
        <ul class="list-unstyled">
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Nombre de usuario:</span>
            {{cliente.user.username}}</li>
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Email:</span> {{cliente.user.email}}</li>
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Teléfono:</span> {{cliente.phone}}</li>
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Fecha de nacimiento:</span>
            {{cliente.birthdate}}</li>
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Fecha de registro:</span>
            {{cliente.user.date_joined}}</li>
          <li class="mb-2" style="font-size: 13px;"><span class="fw-bold">Último login:</span>
            {{cliente.user.last_login}}</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-start w-50">
    <a href="{% url 'clientes:home' %}" type="button" class="btn btn-success w-100">
      Volver
    </a>
  </div>
</div>
{% endblock contenido %}

project/clientes/templates/clientes/client_form.html
{% extends 'core/base.html' %}

{% block title %}
Editar {%if not request.user.is_staff%}Perfil{%else%}Cliente{%endif%} | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center border border-1 rounded-2 w-50 p-4 shadow-sm bg-light">
  <h1 class="fs-3 mb-4">
    Editar {%if not request.user.is_staff%}Perfil{%else%}Cliente{%endif%}
  </h1>
  <form method="post" class="d-flex flex-column w-100" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="d-flex gap-3">
      <div class="form-group w-50">
        <input type="text" name="{{ form.first_name.name }}" class="form-control mb-3"
          id="{{ form.first_name.id_for_label }}"
          value="{% if form.instance.pk %} {{ form.instance.first_name }} {% endif %}">
      </div>
      <div class="form-group w-50">
        <input type="text" name="{{ form.last_name.name }}" class="form-control mb-3"
          id="{{ form.last_name.id_for_label }}"
          value="{% if form.instance.pk %} {{ form.instance.last_name }} {% endif %}">
      </div>
    </div>
    <div class="d-flex gap-3">
      <div class="form-group w-50">
        <input type="date" name="{{ form.birthdate.name }}" class="form-control mb-3"
          id="{{ form.birthdate.id_for_label }}"
          value="{% if form.instance.pk %}{{ form.instance.client.birthdate|date:'Y-m-d' }}{% endif %}">
      </div>
      <div class="form-group w-50">
        <input type="text" name="{{ form.phone.name }}" class="form-control mb-3" id="{{ form.phone.id_for_label }}"
          value="{% if form.instance.pk %} {{ form.instance.client.phone }} {% endif %}">
      </div>
    </div>
    <div class="d-flex gap-3">
      <div class="form-group w-50">
        <input type="text" name="{{ form.username.name }}" class="form-control mb-3"
          id="{{ form.username.id_for_label }}"
          value="{% if form.instance.pk %} {{ form.instance.username }} {% endif %}"">
      </div>
      <div class=" form-group w-50">
        <input type="text" name="{{ form.email.name }}" class="form-control mb-3" id="{{ form.email.id_for_label }}"
          value="{% if form.instance.pk %} {{ form.instance.email }} {% endif %}">
      </div>
    </div>
    <div class="d-flex gap-3">
      <div class="form-group w-50">
        <input type="password" name="{{ form.password.name }}" class="form-control"
          id="{{ form.password.id_for_label }}" placeholder="Contraseña">
        <div id="dateHelp" class="form-text">
          {%if not request.user.is_staff %}
          Si no cambia la contraseña, ingrese su contraseña actual para guardar los cambios.
          {%else%}
          Si no cambia la contraseña, persiste la establecida en el registro.
          {%endif%}
        </div>
      </div>
      <div class="form-group w-50">
        <input type="file" name="{{ form.avatar.name }}" class="form-control" id="{{ form.avatar.id_for_label }}">
        <div id="dateHelp" class="form-text">Si no carga un nuevo avatar, persiste el cargado en el registro.</div>
      </div>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
      {% for field in form %}
      {% for error in field.errors %}
      <p class="mb-2 lh-sm">*{{ error }}</p>
      {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
      <p class="mb-0 lh-sm">*{{ error }}</p>
      {% endfor %}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <div class="d-flex justify-content-center gap-3">
      <button type="submit" class="btn btn-success w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
        </svg>
        Confirmar
      </button>
      <a href="{%if request.user.is_staff %}{% url 'clientes:home' %}{%else%}{% url 'core:home' %}{%endif %}"
        type="button" class="btn btn-danger w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
        </svg>
        Cancelar
      </a>
    </div>
  </form>
</div>
{% endblock contenido %}

project/clientes/templates/clientes/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
Clientes | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex mt-4 justify-content-between w-100">
  <div class="d-flex flex-column align-items-start w-25">
    <h3 class="fs-4">Buscar un cliente</h3>
    <form action="{% url 'clientes:home' %}" method="get" class="d-flex w-100 justify-content-center">
      <input type="text" name="consulta" placeholder="Ingrese un nombre..." class="form-control w-100">
    </form>
  </div>
</div>
<div class="d-flex flex-column align-items-center w-100 h-75 mt-2" style="overflow-y: auto; max-height: 50vh">
  <table class="table">
    <tr class="table-dark">
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Usuario</th>
      <th>Email</th>
      <th>Teléfono</th>
      <th>Acciones</th>
    </tr>
    {% if request.GET.consulta and not clientes %}
    <tr>
      <td colspan="6" class="bg-light">
        <div class="d-flex justify-content-center align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
              d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
          </svg>
          No se encontraron resultados.
        </div>
      </td>
    </tr>
    {% elif not clientes %}
    <tr>
      <td colspan="6" class="bg-light">
        <div class="d-flex justify-content-center align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
              d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
          </svg>
          Aún no hay clientes registrados.
        </div>
      </td>
    </tr>
    {% else %}
    {% for cliente in clientes %}
    <tr>
      <td>{{cliente.first_name}}</td>
      <td>{{cliente.last_name}}</td>
      <td>{{cliente.username}}</td>
      <td>{{cliente.email}}</td>
      <td>{{cliente.client.phone}}</td>
      <td>
        <div class="d-flex gap-4">
          {% if cliente.client.id %}
          <a type="button" class="btn btn-sm m-0 p-0" href="{% url 'clientes:cliente_detail' cliente.client.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill"
              viewBox="0 0 16 16">
              <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" />
              <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7" />
            </svg>
          </a>
          {% endif %}
          {% if not request.user.is_staff %}
          <a type="button" class="btn btn-sm m-0 p-0" href="{% url 'clientes:cliente_update' cliente.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
            </svg>
          </a>
          {% endif %}
      </td>
</div>
</tr>
{% endfor %}
{% endif %}
</table>
{% if request.GET.consulta %}
<a href="{% url 'clientes:home' %}?limpiar" class="d-flex align-items-center gap-2 btn btn-danger ml-2">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill"
    viewBox="0 0 16 16">
    <path
      d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
  </svg>
  Limpiar búsqueda
</a>
{% endif %}
</div>
{% endblock contenido %}