project/catalogo/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'catalogo'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('producto/create/', views.ProductCreate.as_view(), name='producto_create'),
    path('producto/<int:pk>/', views.ProductDetail.as_view(), name='producto_detail'),
    path('producto/<int:pk>/update/', views.ProductUpdate.as_view(), name='producto_update'),
    path('producto/<int:pk>/delete/', views.ProductDelete.as_view(), name='producto_delete'),
]

urlpatterns += [
    path('formato/create/', views.FormatCreate.as_view(), name='formato_create'),
    path('genero/create/', views.GenreCreate.as_view(), name='genero_create'),
]

urlpatterns += staticfiles_urlpatterns()

project/clientes/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'clientes'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('cliente/<int:pk>/update', views.ClientUpdate.as_view(), name='cliente_update'),
    path('cliente/<int:pk>/detail', views.ClienteDetail.as_view(), name='cliente_detail'),
]

urlpatterns += staticfiles_urlpatterns()

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('ordenes/', include('ordenes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

urlpatterns += [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('register/', views.register, name='register'),
]

urlpatterns += staticfiles_urlpatterns()

project/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('order_create/product/<int:pk>/', views.create_order, name='order_create'),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name='order_delete'),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from clientes.models import Client

class CustomAuthenticationForm(AuthenticationForm):
  class Meta:
    model = User
    fields = ['username', 'password']

class CustomUserCreationForm(UserCreationForm):
    phone = forms.CharField(label='Teléfono', required=False)
    birthdate = forms.DateField(label='Fecha de nacimiento', required=False)
    avatar = forms.ImageField(label='Avatar', required=False)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'phone', 'birthdate', 'avatar']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.phone = self.cleaned_data['phone']
        user.birthdate = self.cleaned_data['birthdate']
        if 'avatar' in self.cleaned_data:
            user.avatar = self.cleaned_data['avatar']  # Guardar el avatar solo si está presente en los datos limpios
        if commit:
            user.save()
            client = Client.objects.create(user=user, phone=self.cleaned_data['phone'], 
                                             birthdate=self.cleaned_data['birthdate'], 
                                             avatar=user.avatar)  # Usar user.avatar aquí
        return user
  
class CustomUserChangeForm(forms.ModelForm):
    phone = forms.CharField(label='Teléfono', required=False)
    birthdate = forms.DateField(label='Fecha de nacimiento', required=False)
    avatar = forms.ImageField(label='Avatar', required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password', 'phone', 'birthdate', 'avatar']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        try:
            client = self.instance.client
            self.initial['phone'] = client.phone
            self.initial['birthdate'] = client.birthdate
            self.initial['avatar'] = client.avatar
        except Client.DoesNotExist:
            pass 

    def save(self, commit=True):
        user = super().save(commit=False)
        user.phone = self.cleaned_data['phone']
        user.birthdate = self.cleaned_data['birthdate']
        user.avatar = self.cleaned_data['avatar']
        
        if commit:
            user.save()
            try:
                client = user.client
                client.phone = self.cleaned_data['phone']
                client.birthdate = self.cleaned_data['birthdate']
                client.avatar = self.cleaned_data['avatar']
                client.save()
            except Client.DoesNotExist:
                pass
        return user

project/core/views.py
from django.shortcuts import redirect, render
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.contrib.auth.views import LoginView

def home(request):
  return render(request, 'core/index.html')

def about(request):
  return render(request, 'core/about.html')

class CustomLoginView(LoginView):
  autentication_form = CustomAuthenticationForm
  template_name = 'core/login.html'

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('core:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'core/register.html', {'form': form})

project/core/templates/core/components/footer.html
<footer class="d-flex py-5 bg-dark">
  <div class="container px-2 d-flex justify-content-between">
    <div class="d-flex flex-column align-items-start justify-content-end">
      <p class="m-0 text-center text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill"
          viewBox="0 0 16 16">
          <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6" />
        </svg>
        San Martín 1123 - Santa Fe - Argentina
      </p>
      <p class="m-0 text-center text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-whatsapp"
          viewBox="0 0 16 16">
          <path
            d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232" />
        </svg>
        + 549 342 2345-6789
      </p>
      <p class="m-0 text-center text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
          class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
          <path
            d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2zm-2 9.8V4.698l5.803 3.546zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.5 4.5 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586zM16 9.671V4.697l-5.803 3.546.338.208A4.5 4.5 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671" />
          <path
            d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791" />
        </svg>
        discos@hexagramdisqueria.com.ar
      </p>
    </div>
    <div class="d-flex flex-column align-items-end justify-content-end">
      <p class="m-0 text-center text-white">Copyright &copy; 2024</p>
      <p class="m-0 text-center text-white">Desarrollado por Rodrigo Carlachiani</p>
    </div>
  </div>
</footer>

project/core/templates/core/components/navbar.html
{% load static %}

<nav class="d-flex navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-5 h-100">
    <a class="navbar-brand fw-bold d-flex align-items-center " href="{% url 'core:home' %}">
      <img class="me-2" src="{% static 'core/img/hexagram-logo-navbar.webp' %}" alt="Logo de la disquería">
      <p class="p-0 m-0 ">Hexagram Disquería</p>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
        </li>
        {% if not user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:about' %}">Nosotros</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalogo:home' %}">Catálogo</a>
        </li>
        {% if user.is_authenticated %}
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'clientes:home' %}">Clientes</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ordenes:home' %}">{%if not user.is_staff%}Mis {%endif%}Órdenes</a>
        </li>
        <li class="nav-item ms-3">
          <div class="dropdown">
            <button class="btn btn-success " type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="d-flex gap-2">
                {{ user.username }}
                {% if user.is_staff or not user.client.avatar %}
                <img style="width: 25px;" src="{% static 'core/img/avatar_default.webp' %}" alt="Avatar administrador">
                {% else %}
                <img style="width: 25px; border-radius: 50%;" src="{{ user.client.avatar.url }}" alt="Avatar cliente">
                {% endif %}
              </div>
            </button>
            <ul class="dropdown-menu">
              <li>
                {%if not user.is_staff%}
                <a class="dropdown-item" href="{% url 'clientes:cliente_update' request.user.id %}">
                  Editar perfil
                </a>
                {%endif %}
                <a class="dropdown-item" href="{% url 'core:logout' %}">Cerrar sesión</a>
              </li>
            </ul>
          </div>
        </li>
        {% else %}
        <li class="nav-item ms-3">
          <a class="btn btn-outline-success nav-link" href="{% url 'core:login' %}">Iniciar sesión</a>
        </li>
        <li class="nav-item ms-3">
          <a class="btn btn-outline-info  nav-link" href="{% url 'core:register' %}">Registrarse</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>