project/catalogo/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'catalogo'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('producto/create/', views.ProductCreate.as_view(), name='producto_create'),
    path('producto/<int:pk>/', views.ProductDetail.as_view(), name='producto_detail'),
    path('producto/<int:pk>/update/', views.ProductUpdate.as_view(), name='producto_update'),
    path('producto/<int:pk>/delete/', views.ProductDelete.as_view(), name='producto_delete'),
]

urlpatterns += [
    path('formato/create/', views.FormatCreate.as_view(), name='formato_create'),
    path('genero/create/', views.GenreCreate.as_view(), name='genero_create'),
]

urlpatterns += staticfiles_urlpatterns()

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('ordenes/', include('ordenes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

urlpatterns += [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('register/', views.register, name='register'),
]

urlpatterns += staticfiles_urlpatterns()

project/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('order_create/product/<int:pk>/', views.create_order, name='order_create'),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name='order_delete'),
]

project/catalogo/models.py
from django.db import models
  
class Format(models.Model):
  name = models.CharField(max_length=100, unique=True, verbose_name='Nombre')

  def __str__(self):
    return self.name
  
class Genre(models.Model):
  name = models.CharField(max_length=100, unique=True, verbose_name='Nombre')

  def __str__(self):
    return self.name
  
class Product(models.Model):
  name = models.CharField(max_length=100, verbose_name='Nombre')
  price = models.IntegerField(verbose_name='Precio')
  format = models.ForeignKey(Format, on_delete=models.CASCADE, verbose_name='Formato')
  genre = models.ForeignKey(Genre, on_delete=models.CASCADE, verbose_name='Género')
  stock = models.IntegerField(default=0, verbose_name='Stock')
  image = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='Imagen')

  def __str__(self):
    return f"{self.name} - {self.format} - {self.genre} - U$S{self.price}"

project/catalogo/forms.py
from django import forms
from . import models

class FormatForm(forms.ModelForm):
    class Meta:
        model = models.Format
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

class GenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'price': forms.NumberInput(attrs={'class': 'form-control mb-2'}),
            'format': forms.Select(choices=models.Format.objects.all(), attrs={'class': 'form-control'}),
            'genre': forms.Select(choices=models.Genre.objects.all(), attrs={'class': 'form-control'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['format'].empty_label = 'Seleccione un formato'
        self.fields['genre'].empty_label = 'Seleccione un género'

project/catalogo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from . import models, forms

class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff
    
    def handle_no_permission(self):
        return redirect('core:home')

def home(request):
    consulta = request.GET.get('consulta')
    if consulta:
        productos = models.Product.objects.filter(name__icontains=consulta)
    else:
        productos = models.Product.objects.all()
    context = {
        'productos': productos,
        'consulta_actual': consulta
    }
    if 'limpiar' in request.GET:  
        return redirect('catalogo:home')
    return render(request, 'catalogo/index.html', context)

class FormatCreate(LoginRequiredMixin, StaffRequiredMixin, CreateView):
  model = models.Format
  form_class = forms.FormatForm
  success_url = reverse_lazy('catalogo:home')

class GenreCreate(LoginRequiredMixin, StaffRequiredMixin, CreateView):
  model = models.Genre
  form_class = forms.GenreForm
  success_url = reverse_lazy('catalogo:home')

class ProductCreate(LoginRequiredMixin, StaffRequiredMixin, CreateView):
  model = models.Product
  form_class = forms.ProductForm
  success_url = reverse_lazy('catalogo:home')
  def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.image = self.request.FILES.get('image')
        self.object.save()
        return super().form_valid(form)

class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = models.Product
    form_class = forms.ProductForm
    success_url = reverse_lazy('catalogo:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if 'image' in self.request.FILES:
            self.object.image = self.request.FILES['image']
        else:
            previous_instance = models.Product.objects.get(pk=self.object.pk)
            self.object.image = previous_instance.image
        self.object.save()
        return super().form_valid(form)

class ProductDetail(DetailView):
  model = models.Product
  context_object_name = 'producto'

class ProductDelete(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
  model = models.Product
  success_url = reverse_lazy('catalogo:home')

project/catalogo/templates/catalogo/format_form.html
{% extends 'core/base.html' %}

{% block title %}
Añadir Formato | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center border border-1 rounded-2 w-25 p-4 shadow-sm bg-light">
  <h2 class="mb-3 fs-4">Añadir Formato</h2>
  <form method="post" class="d-flex flex-column w-100">
    {% csrf_token %}
    {{ form.name }}
    <div id="dateHelp" class="form-text">Boxset, LP, 7", 10", CD, Cassette, etc.</div>
    <div class="d-flex justify-content-center gap-3">
      <button type="submit" class="btn btn-success w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
        </svg>
        Confirmar
      </button>
      <a href="{% url 'catalogo:home' %}" type="button"
        class="btn btn-danger w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
        </svg>
        Cancelar
      </a>
    </div>
  </form>
</div>
{% endblock contenido %}

project/catalogo/templates/catalogo/genre_form.html
{% extends 'core/base.html' %}

{% block title %}
Añadir Género | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center border border-1 rounded-2 w-25 p-4 shadow-sm bg-light">
  <h2 class="mb-3 fs-4">Añadir Género</h2>
  <form action="" method="post" class="d-flex flex-column w-100">
    {% csrf_token %}
    {{ form.name.label }}{{ form.name }}
    <div id="dateHelp" class="form-text">Rock, Pop, Punk, Folk, Metal, Funk, Jazz, etc.</div>
    <div class="d-flex justify-content-center gap-3">
      <button type="submit" class="btn btn-success w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
        </svg>
        Confirmar
      </button>
      <a href="{% url 'catalogo:home' %}" type="button"
        class="btn btn-danger w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
        </svg>
        Cancelar
      </a>
    </div>
  </form>
</div>
{% endblock contenido %}

project/catalogo/templates/catalogo/index.html
{% extends 'core/base.html' %}

{% block title %}
Catálogo | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex mt-4 justify-content-between w-100">
  <div class="d-flex flex-column align-items-start w-25">
    <h3 class="fs-4">Buscar un producto</h3>
    <form action="{% url 'catalogo:home' %}" method="get" class="d-flex w-100 justify-content-center">
      <input type="text" name="consulta" placeholder="Ingrese título o artista..." class="form-control w-100">
    </form>
  </div>
  {% if user.is_staff %}
  <div class="d-flex w-50 justify-content-end align-items-end gap-3">
    <a class="d-flex align-items-center gap-2 btn btn-success" href="{% url 'catalogo:formato_create' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
        <path
          d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
      </svg>
      Añadir Formato
    </a>
    <a class="d-flex align-items-center gap-2 btn btn-success" href="{% url 'catalogo:genero_create' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
        <path
          d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
      </svg>
      Añadir Género
    </a>
    <a class="d-flex align-items-center gap-2 btn btn-success" href="{% url 'catalogo:producto_create' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
        <path
          d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
      </svg>
      Añadir Producto
    </a>
  </div>
  {% endif %}
</div>
<div class="d-flex flex-column align-items-center w-100 h-75 mt-2" style="overflow-y: auto; max-height: 50vh">
  <table class="table">
    <tr class="table-dark">
      <th>Nombre</th>
      <th>Género</th>
      <th>Formato</th>
      <th>Precio</th>
      <th>Stock</th>
      <th>Acciones</th>
    </tr>
    {% if request.GET.consulta and not productos %}
    <tr>
      <td colspan="6" class="bg-light">
        <div class="d-flex justify-content-center align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
              d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
          </svg>
          No se encontraron resultados.
        </div>
      </td>
    </tr>
    {% elif not productos %}
    <tr>
      <td colspan="6" class="bg-light">
        <div class="d-flex justify-content-center align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
              d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
          </svg>
          Aún no se han cargado productos al catálogo.
        </div>
      </td>
    </tr>
    {% else %}
    {% for producto in productos %}
    <tr>
      <td>{{producto.name}}</td>
      <td>{{producto.genre}}</td>
      <td>{{producto.format}}</td>
      <td>U$S{{producto.price}}</td>
      <td>{{producto.stock}}</td>
      <td>
        <div class="d-flex gap-4">
          <a type="button" class="btn btn-sm m-0 p-0" href="{% url 'catalogo:producto_detail' producto.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill"
              viewBox="0 0 16 16">
              <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" />
              <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7" />
            </svg>
          </a>
          {% if user.is_staff %}
          <a type="button" class="btn btn-sm m-0 p-0" href="{% url 'catalogo:producto_update' producto.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd"
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
            </svg>
          </a>
          <a type="button" class="btn btn-sm m-0 p-0" href="{% url 'catalogo:producto_delete' producto.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill"
              viewBox="0 0 16 16">
              <path
                d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
            </svg>
          </a>
          {% endif %}
        </div>
      </td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
  {% if request.GET.consulta %}
  <a href="{% url 'catalogo:home' %}?limpiar" class="d-flex align-items-center gap-2 btn btn-danger ml-2">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill"
      viewBox="0 0 16 16">
      <path
        d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
    </svg>
    Limpiar búsqueda
  </a>
  {% endif %}
</div>
{% endblock contenido %}

project/catalogo/templates/catalogo/product_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
Eliminar Producto | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center w-100">
  <h2 class="mb-3">¿Desea eliminar el producto seleccionado?</h2>
  <form method="post" class="d-flex flex-column w-25">
    {% csrf_token %}
    <div class="d-flex justify-content-center gap-3">
      <button type="submit" class="btn btn-success w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
        </svg>
        Confirmar
      </button>
      <a href="{% url 'catalogo:home' %}" type="button"
        class="btn btn-danger w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
        </svg>
        Cancelar
      </a>
    </div>
  </form>
</div>
{% endblock contenido %}

project/catalogo/templates/catalogo/product_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
{{ producto.name }} | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center gap-4 w-100">
  <div class="d-flex flex-column align-items-center border border-1 rounded-2 w-50 py-4 px-5 shadow-sm bg-light">
    <h2 class="mb-4 fs-2">{{ producto.name }}</h2>
    <div class="d-flex w-100 gap-4 justify-content-between">
      <div class="d-flex flex-column">
        {% if producto.image %}
        <img src="{{ producto.image.url }}" alt="Imagen del producto" style="width: 250px; border-radius: 10px;">
        {% else %}
        <img src="{% static 'core/img/default-product.webp' %}" alt="Imagen del producto por defecto"
          style="width: 250px; border-radius: 10px;">
        {% endif %}
      </div>
      <div class="d-flex flex-column w-100">
        <ul class="list-unstyled">
          <li class="mb-2"><span class="fw-bold">Precio:</span> U$S{{ producto.price }}</li>
          <li class="mb-2"><span class="fw-bold">Formato:</span></span> {{ producto.format }}</li>
          <li class="mb-2"><span class="fw-bold">Género:</span></span> {{ producto.genre }}</li>
          <li class="mb-2"><span class="fw-bold">Stock:</span"></span> {{ producto.stock }}</li>
        </ul>
        {% if not user.is_staff %}
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'ordenes:order_create' producto.id %}" class="d-flex align-items-end gap-3">
          {% csrf_token %}
          <div class="d-flex flex-column w-25">
            <label for="quantity" class="form-label">Cant.:</label>
            <input type="number" {%if producto.stock is 0%}disabled{%else%}min="1" value="1" {%endif%} id="quantity"
              name="quantity" class="form-control form-control-sm">
          </div>
          <button type="submit" class="btn btn-sm btn-success w-50 d-flex align-items-center justify-content-center"
            {%if producto.stock is 0%} disabled {%endif%}>
            <div class="d-flex gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4"
                viewBox="0 0 16 16">
                <path
                  d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2H8zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0" />
              </svg>
              <p class="p-0 m-0">Ordenar</p>
            </div>
          </button>
        </form>
        {% if error_message %}
        <div id="errorHelp" class="form-text text-danger pt-2">*{{error_message}}</div>
        {% endif %}
        {% else %}
        <p class="text-danger mb-2" style="font-size: 13px;">*Para ordenar éste producto,<br> inicie sesión.</p>
        <a href="{% url 'core:login' %}" class="btn btn-success d-flex align-items-center justify-content-center w-75">
          <div class="d-flex gap-3 align-items-center justify-content-center">
            <img src="{% static 'core/img/avatar_default.webp' %}" style="width: 25px; height: 25px;"
              alt="Avatar inicio de sesión">
            <p class="p-0 m-0" style="font-size: 13px;">Iniciar sesión</p>
          </div>
        </a>
        {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-start w-50">
    <a href="{% url 'catalogo:home' %}" type="button" class="btn btn-success w-100">
      Volver
    </a>
  </div>
</div>
{% endblock contenido %}