project/catalogo/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'catalogo'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('producto/create/', views.ProductCreate.as_view(), name='producto_create'),
    path('producto/<int:pk>/', views.ProductDetail.as_view(), name='producto_detail'),
    path('producto/<int:pk>/update/', views.ProductUpdate.as_view(), name='producto_update'),
    path('producto/<int:pk>/delete/', views.ProductDelete.as_view(), name='producto_delete'),
]

urlpatterns += [
    path('formato/create/', views.FormatCreate.as_view(), name='formato_create'),
    path('genero/create/', views.GenreCreate.as_view(), name='genero_create'),
]

urlpatterns += staticfiles_urlpatterns()

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('clientes.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('ordenes/', include('ordenes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

urlpatterns += [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('register/', views.register, name='register'),
]

urlpatterns += staticfiles_urlpatterns()

project/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('order_create/product/<int:pk>/', views.create_order, name='order_create'),
    path('order_delete/<int:pk>/', views.OrderDelete.as_view(), name='order_delete'),
]

project/ordenes/models.py
from django.db import models
from django.forms import ValidationError
from django.utils import timezone
from clientes.models import Client
from catalogo.models import Product

class Order(models.Model):
  client = models.ForeignKey(Client, on_delete=models.DO_NOTHING, related_name='orders')
  product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
  quantity = models.PositiveIntegerField()
  total_price = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
  order_date = models.DateTimeField(default=timezone.now, editable=False)

  class Meta:
    ordering = ['-order_date']

  def full_clean(self):
    if self.quantity > self.product.stock:
      raise ValidationError('La cantidad solicitada supera el stock disponible.')
    
  def save(self, *args, **kwargs):
    self.total_price = self.product.price * self.quantity
    self.product.stock -= self.quantity
    self.product.save() 
    super().save(*args, **kwargs)

project/ordenes/forms.py
from django import forms
from . import models

class OrderForm(forms.ModelForm):
  class Meta:
    model = models.Order
    fields = '__all__'

project/ordenes/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from catalogo import models
from . import models

class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff
    
    def handle_no_permission(self):
        return redirect('core:home')

@login_required
def home(request):
  if request.user.is_staff:
    orders = models.Order.objects.all()
    return render(request, 'ordenes/index.html', {'ordenes': orders})
  else:
    cliente = request.user.client
    orders = models.Order.objects.filter(client=cliente)
    return render(request, 'ordenes/index.html', {'ordenes': orders})
  
@login_required
def create_order(request, pk):
    product = get_object_or_404(models.Product, pk=pk)
    quantity = request.POST.get('quantity', 1) 
    order = models.Order(
        client=request.user.client,
        product=product,
        quantity=int(quantity)
    )
    try:
        order.full_clean()
        order.save()
        return render(request, 'ordenes/order_success.html', {'producto': product, 'quantity': quantity})
    except ValidationError:
        return render(request, 'catalogo/product_detail.html', {'producto': product, 'error_message': 'La cantidad solicitada supera el stock disponible.'})
    
class OrderDelete(LoginRequiredMixin, DeleteView):
  model = models.Order
  success_url = reverse_lazy('ordenes:home')

project/ordenes/templates/ordenes/index.html
{% extends 'core/base.html' %}

{% block title %}
{% if request.user.is_staff %}
Órdenes
{% else %}
Mis Órdenes
{% endif %}
| Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex mt-4 justify-content-between w-100">
  <h3 class="fs-4 text-start">
    {% if request.user.is_staff %}
    Órdenes
    {% else %}
    Mis Órdenes
    {% endif %}
  </h3>
</div>
<div class="d-flex flex-column align-items-center w-100 h-75 mt-2" style="overflow-y: auto; max-height: 50vh">
  <table class="table">
    <tr class="table-dark">
      {% if request.user.is_staff %}
      <th>Cliente</th>
      {% endif %}
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio total</th>
      <th>Fecha de orden</th>
      <th>Acciones</th>
    </tr>
    {% if not ordenes %}
    <tr>
      <td colspan="6" class="bg-light">
        <div class="d-flex justify-content-center align-items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
            <path
              d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5m.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
          </svg>
          Aún no {%if request.user.is_staff%}han{%else%}has{%endif%} realizado ninguna orden.
        </div>
      </td>
    </tr>
    {% else %}
    {% for orden in ordenes %}
    <tr>
      {% if request.user.is_staff %}
      <td>{{orden.client.user.first_name}} {{orden.client.user.last_name}}</td>
      {% endif %}
      <td>{{orden.product.name}} - {{orden.product.format}} - U$S{{orden.product.price}}</td>
      <td>{{orden.quantity}}</td>
      <td>U$S{{orden.total_price}}</td>
      <td>{{orden.order_date}}</td>
      <td>
        <div class="d-flex">
          <a type=" ubmit" class="btn btn-sm m-0 p-0" href="{% url 'ordenes:order_delete' orden.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill"
              viewBox="0 0 16 16">
              <path
                d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
            </svg>
          </a>
        </div>
      </td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
</div>
{% endblock contenido %}

project/ordenes/templates/ordenes/order_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
Dar de baja orden | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center w-100">
  <h2 class="mb-3">¿Desea dar de baja la orden seleccionada?</h2>
  <form method="post" class="d-flex flex-column w-25">
    {% csrf_token %}
    <div class="d-flex justify-content-center gap-3">
      <button type="submit" class="btn btn-success w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05" />
        </svg>
        Confirmar
      </button>
      <a href="{% url 'ordenes:home' %}" type="button"
        class="btn btn-danger w-50 mt-4 d-flex justify-content-center align-items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle"
          viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
          <path
            d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
        </svg>
        Cancelar
      </a>
    </div>
  </form>
</div>
{% endblock contenido %}

project/ordenes/templates/ordenes/order_success.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}
Orden exitosa | Hexagram Disquería
{% endblock title %}

{% block contenido %}
<div class="d-flex flex-column align-items-center gap-4 w-100">
  <div class="d-flex flex-column align-items-center">
    <h1 class="mb-5">
      Orden creada con éxito
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart-check ms-2"
        viewBox="0 0 16 16">
        <path
          d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0z" />
        <path
          d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0" />
      </svg>
    </h1>
    <p class="fs-4 fw-bold mb-5">
      {{ producto.name }} - {{ producto.format }} <span class="fs-6">(x{{ quantity }}u.)</span>
    </p>
    <p class="text-center mb-5">En breve nos comunicaremos a través de alguno de los medios de contacto registrados<br>
      para proceder con el método de pago y entrega.</p>
    <p class="fw-bold ">¡Muchas Gracias!</p>
  </div>
  <div class="d-flex justify-content-between w-50 gap-3">
    <div class="d-flex justify-content-start w-50">
      <a href="{% url 'catalogo:home' %}" type="button" class="btn btn-success w-100">
        Volver al catálogo
      </a>
    </div>
    <div class="d-flex justify-content-start w-50">
      <a href="{% url 'ordenes:home' %}" type=" button" class="btn btn-success w-100">
        Ir a mis órdenes
      </a>
    </div>
  </div>
</div>
{% endblock contenido %}